## PMW3610 Driver (280Zo fork, ALT variant)
## https://github.com/280Zo/zmk-pmw3610-driver
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y

## 如果上电后日志出现 "Incorrect product id 0xFF (expecting 0x3E)"，取消下面这行注释
# CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=1000

## 调试日志（需要时取消注释）
# CONFIG_LOG=y
# CONFIG_LOG_DEFAULT_LEVEL=3
# CONFIG_PMW3610_ALT_LOG_LEVEL_DBG=y
